#ifndef ALECTRNN_COMMON_NERVOUS_SYSTEM_HANDLER_H_
#define ALECTRNN_COMMON_NERVOUS_SYSTEM_HANDLER_H_

#include <Python.h>

PyMODINIT_FUNC PyInit_nn_handler(void);

#endif /* ALECTRNN_COMMON_NERVOUS_SYSTEM_HANDLER_H_ */
